<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumFileRepository extends EntityRepository
{
}
