<?php

namespace AppBundle\Repository;

/**
 * AlbumFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumFileRepository extends \Doctrine\ORM\EntityRepository
{
}
