<?php

namespace AppBundle\Repository;

use DateTime;
use Doctrine\Common\Collections\Criteria;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllStartingFromThisMonth() {
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->gt('date', new DateTime("last day of previous month")));
        $criteria->orderBy(array('date' => 'ASC'));
        return $this->matching($criteria);
    }
}
